### ISSUE TITLE
项目中存在的问题

### ISSUE THREAD

**Issue by hempflower** [POI5U/ist-exmaine-4#1]
### 问题描述

目前项目中包含了许多与解算无关的代码(例如单片机库、MPU驱动)，更像是一个驱动 MPU6050 的例程，而不是一个姿态解算库。如果现在想要在其他项目中使用，会无从下手。

### 改进建议

1. 应该把算法部分单独提取出来 
2. 根据算法特点先设计一组 API
3. 保证库的职责单一。例如算法定时运行、数据获取等功能应该由使用者自己实现。

不过考虑到可能缺少这方面的经验，这里有一份 PID 库的代码，可以参考下 API 的设计。

[参考用PID库.zip](https://github.com/POI5U/ist-exmaine-4/files/13178244/pid_lib.zip)

**Comment by POI5U** [comment]
@hempflower 好的, 感谢建议 !
